version: "3"

services:
    nginx:
        image: nginx
        restart: unless-stopped
        ports:
            - 9001:9001
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - authservice
            - postservice
            - storyservice

    authservice:
        build: ./authentication
        restart: unless-stopped
        environment:
            DB_URL: mongodb://authdb:27017/authservice
        depends_on:
            - authdb

    authdb:
        image: mongo
        ports:
            - 27018:27017
        restart: unless-stopped
        volumes:
            - /auth:/data/db

    postservice:
        build: ./post
        restart: unless-stopped
        environment:
            DB_URL: mongodb://postdb:27017/postservice
        depends_on:
            - authservice
            - postdb

    postdb:
        image: mongo
        ports:
            - 27019:27017
        restart: unless-stopped
        volumes:
            - /post:/data/db

    storyservice:
        build: ./story
        restart: unless-stopped
        environment:
            DB_URL: mongodb://storydb:27017/storyservice
        depends_on:
            - authservice
            - storydb
            - storyobjectdb

    storydb:
        image: mongo
        ports:
            - 27020:27017
        volumes:
            - /story:/data/db
        restart: unless-stopped

    storyobjectdb:
        image: minio/minio:latest
        ports:
            - 9000:9000
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server --address 127.0.0.1:9000 /data

    mc:
        image: minio/mc:latest
        depends_on:
            - storyobjectdb
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
            /usr/bin/mc rm -r --force myminio/minifb;
            /usr/bin/mc mb myminio/minifb;
            /usr/bin/mc policy set public myminio/minifb;
            exit 0;
            "
