version: "3"

services:
    nginx:
        image: nginx
        restart: unless-stopped
        ports:
            - 1000:9001
        volumes:
            - ./nginx.conf:/etc/nginx/sites-enabled/app
        depends_on:
            - authservice
            - postservice
            - storyservice

    authservice:
        container_name: authservice
        build: ./authentication
        restart: unless-stopped
        environment:
            - DB_CONNECT_LOCAL=mongodb://authdb:27017/miniFBauth
        depends_on:
            - authdb

    authdb:
        container_name: authdb
        image: mongo
        ports:
            - 27017:27017
        restart: unless-stopped
        volumes:
            - /mongo:/data/db

    postservice:
        container_name: postservice
        build: ./post
        restart: unless-stopped
        depends_on:
            - postdb

    postdb:
        container_name: postdb
        image: mongo
        ports:
            - 27019:27017
        restart: unless-stopped
        volumes:
            - /mongo:/data/db

    storyservice:
        container_name: storyservice
        build: ./story
        restart: unless-stopped
        depends_on:
            - storydb
            - storyobjectdb

    storydb:
        container_name: storydb
        image: mongo
        ports:
            - 27020:27017
        volumes:
            - /mongo:/data/db
        restart: unless-stopped

    storyobjectdb:
        image: minio/minio:latest
        environment:
            - MINIO_ACCESS_KEY=w6cNXuAj9BGXOCyo
            - MINIO_SECRET_KEY=Vyl6KQoQzGJWT28ngX2T0s9SwjjzWtMV
        command: server --address 127.0.0.1:9000 /data
