version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        restart: unless-stopped
        ports:
            - 100:100
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - authservice
            - postservice
            - storyservice

    authservice:
        container_name: authservice
        build: ./authentication
        restart: unless-stopped
        environment:
            DB_URL: mongodb://authdb:27017/authservice
        depends_on:
            - authdb

    authdb:
        container_name: authdb
        image: mongo
        ports:
            - 27018:27017
        restart: unless-stopped
        volumes:
            - /auth:/data/db

    postservice:
        container_name: postservice
        build: ./post
        restart: unless-stopped
        environment:
            DB_URL: mongodb://postdb:27017/postservice
        depends_on:
            - authservice
            - postdb

    postdb:
        container_name: postdb
        image: mongo
        ports:
            - 27019:27017
        restart: unless-stopped
        volumes:
            - /post:/data/db

    storyservice:
        container_name: storyservice
        build: ./story
        restart: unless-stopped
        environment:
            DB_URL: mongodb://storydb:27017/storyservice
        depends_on:
            - authservice
            - storydb
            - storyobjectdb

    storydb:    
        container_name: storydb
        image: mongo
        ports:
            - 27020:27017
        volumes:
            - /story:/data/db
        restart: unless-stopped

    storyobjectdb:
        container_name: storyobjectdb
        image: minio/minio:latest
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server --console-address ":9001" /data
        volumes:
            - /minio_data:/data

volumes:
    auth:
    post:
    story: